from __future__ import (
    annotations,
)

from dataclasses import (
    dataclass,
)
from pathlib import (
    Path,
)
import os
import tempfile


GENERATED_MARKER = "# GENERATED BY intent"


@dataclass(frozen=True)
class OwnershipError(RuntimeError):
    path: Path
    message: str

    def __str__(
        self,
    ) -> str:
        return f"{self.path}: {self.message}"


def _is_tool_owned(
    text: str,
    marker: str = GENERATED_MARKER,
) -> bool:
    return marker in text


def _atomic_write_text(
    path: Path,
    content: str,
    encoding: str = "utf-8",
) -> None:
    """
    Write content atomically: write to a temp file in the same directory, then replace.
    This avoids partially-written files if the process is interrupted
    """
    directory = path.parent
    directory.mkdir(
        parents=True,
        exist_ok=True,
    )

    (
        fd,
        tmp_name,
    ) = tempfile.mkstemp(
        prefix=".intent.",
        dir=str(directory),
    )
    tmp_path = Path(tmp_name)

    try:
        with os.fdopen(
            fd,
            "w",
            encoding=encoding,
            newline="\n",
        ) as f:
            f.write(content)
        os.replace(
            tmp_path,
            path,
        )  # atomic on POSIX when same filesystem
    finally:
        # if something failed before replace, clean up temp file
        if tmp_path.exists():
            try:
                tmp_path.unlink()
            except OSError:
                pass


def write_generated_file(
    path: Path,
    content: str,
    marker: str = GENERATED_MARKER,
) -> bool:
    """
    Write a tool-generated file safely.

    Returns True if the file was written/updated, False if no change.

    Safety rules:
    - Refuse to overwrite an existing file if it is not tool-owned (missing marker).
    - Refuse to write if the *new* content does not include the marker.
    - If content is identical, do nothing (idempotent).
    """
    if marker not in content:
        raise ValueError(f"Refusing to write {path}: generated content missing marker {marker!r}")

    if path.exists():
        existing = path.read_text(encoding="utf-8")
        if not _is_tool_owned(
            existing,
            marker=marker,
        ):
            raise OwnershipError(
                path=path,
                message=f"Refusing to overwrite: file is not marked as generated ({marker})",
            )
        if existing == content:
            return False
        _atomic_write_text(
            path,
            content,
        )
        return True

    _atomic_write_text(
        path,
        content,
    )
    return True
