from __future__ import annotations

from intent.config import IntentConfig


def render_just(cfg: IntentConfig) -> str:
    """
    Render a minimal justfile as a string.

    Projection only:
    - no filesystem writes
    - no guessing
    """
    lines: list[str] = []

    # Ownership header (justfile supports comments with #)
    lines.append("# GENERATED BY intent")
    lines.append("# DO NOT EDIT")
    lines.append("")

    # Optional: a default recipe to list available commands
    lines.append("default:")
    lines.append('    @just --list')
    lines.append("")

    # One recipe per command
    for name, cmd in cfg.commands.items():
        lines.append(f"{name}:")
        lines.append(f"    {cmd}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"
