from __future__ import annotations

from .config import IntentConfig


def render_ci(cfg: IntentConfig) -> str:
    """
    Render a minimal GitHub Actions workflow as a string.

    Projection only:
    - no filesystem writes
    - no dependency installation
    - no guessing
    """
    lines: list[str] = []

    # Ownership header
    lines.append("# GENERATED BY intent")
    lines.append("# DO NOT EDIT")
    lines.append("")

    # Minimal workflow
    lines.append("name: CI")
    lines.append("on: [push]")
    lines.append("")
    lines.append("jobs:")
    lines.append("  ci:")
    lines.append("    runs-on: ubuntu-latest")
    lines.append("    steps:")
    lines.append("      - uses: actions/checkout@v4")
    lines.append("      - uses: actions/setup-python@v5")
    lines.append("        with:")
    lines.append(f'          python-version: "{cfg.python_version}"')
    lines.append("")

    # One step per command (deterministic: keep insertion order)
    for name, cmd in cfg.commands.items():
        lines.append(f"      - name: {name}")
        lines.append(f"        run: {cmd}")
        lines.append("")

    # Join with newlines
    return "\n".join(lines).rstrip() + "\n"
