from __future__ import annotations

from pathlib import Path

from typer.testing import CliRunner

from intent.cli import app

runner = CliRunner()


def write_pyproject(tmp_path: Path, content: str) -> None:
    (tmp_path / "pyproject.toml").write_text(content, encoding="utf-8")


def test_init_creates_default_intent_file(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.chdir(tmp_path)

    result = runner.invoke(app, ["init"])
    assert result.exit_code == 0

    content = (tmp_path / "intent.toml").read_text(encoding="utf-8")
    assert "[intent]" in content
    assert "schema_version = 1" in content
    assert '[python]' in content
    assert 'version = "3.12"' in content
    assert '[commands]' in content
    assert "[policy]" in content
    assert "strict = false" in content


def test_init_from_existing_infers_python_from_pyproject_lower_bound(
    tmp_path: Path, monkeypatch
) -> None:
    monkeypatch.chdir(tmp_path)
    write_pyproject(
        tmp_path,
        """
        [project]
        name = "x"
        version = "0.0.0"
        requires-python = ">=3.11,<3.13"
        """,
    )

    result = runner.invoke(app, ["init", "--from-existing"])
    assert result.exit_code == 0

    content = (tmp_path / "intent.toml").read_text(encoding="utf-8")
    assert 'version = "3.11"' in content
    assert "(pyproject)" in result.output


def test_init_refuses_overwrite_without_force(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.chdir(tmp_path)
    (tmp_path / "intent.toml").write_text("[python]\nversion='3.10'\n", encoding="utf-8")

    result = runner.invoke(app, ["init"])
    assert result.exit_code == 2
    assert "[INTENT005]" in result.output


def test_init_force_overwrites_existing_file(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.chdir(tmp_path)
    (tmp_path / "intent.toml").write_text("[python]\nversion='3.10'\n", encoding="utf-8")

    result = runner.invoke(app, ["init", "--force"])
    assert result.exit_code == 0

    content = (tmp_path / "intent.toml").read_text(encoding="utf-8")
    assert 'version = "3.12"' in content


def test_init_with_tox_starter_writes_tox_ini(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.chdir(tmp_path)

    result = runner.invoke(app, ["init", "--starter", "tox"])
    assert result.exit_code == 0
    assert "Wrote tox.ini" in result.output
    tox_content = (tmp_path / "tox.ini").read_text(encoding="utf-8")
    assert "# GENERATED BY intent" in tox_content
    assert "[tox]" in tox_content
    assert "envlist = py312" in tox_content


def test_init_with_nox_starter_writes_noxfile(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.chdir(tmp_path)

    result = runner.invoke(app, ["init", "--starter", "nox"])
    assert result.exit_code == 0
    assert "Wrote noxfile.py" in result.output
    nox_content = (tmp_path / "noxfile.py").read_text(encoding="utf-8")
    assert "# GENERATED BY intent" in nox_content
    assert "@nox.session" in nox_content


def test_init_starter_refuses_user_owned_existing_file(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.chdir(tmp_path)
    (tmp_path / "tox.ini").write_text("[tox]\nenvlist = py312\n", encoding="utf-8")

    result = runner.invoke(app, ["init", "--starter", "tox"])
    assert result.exit_code == 1
    assert "[INTENT004]" in result.output
