# test_render_just.py
from intent.config import (
    IntentConfig,
)
from intent.render_just import (
    render_just,
)


def test_render_just_contains_header_and_default() -> None:
    cfg = IntentConfig(
        python_version="3.12",
        commands={"test": "pytest -q"},
    )

    out = render_just(cfg)

    assert "# GENERATED BY intent" in out
    assert "# DO NOT EDIT" in out
    assert "default:" in out
    assert "@just --list" in out


def test_render_just_includes_commands() -> None:
    cfg = IntentConfig(
        python_version="3.12",
        commands={
            "test": "pytest -q",
            "lint": "ruff check .",
        },
    )

    out = render_just(cfg)

    assert "test:" in out
    assert "pytest -q" in out
    assert "lint:" in out
    assert "ruff check ." in out
